### ISSUE TITLE
Blockchain for intelligence?

### ISSUE THREAD

**Issue by Legionof7** [GSA/emerging-technology-atlas#43]
Are there any noncommercial research documents regarding the use of blockchain for the intelligence community?

Services like Augur, TCR's, etc. bring to mind the Good Judgement Project (part of an IARPA program) and I was wondering if there's been any research in this area.

**Comment by ryanwoldatwork** [comment]
Hi @Legionof7, thank you for your question.

I'm also curious to know the answer to your question. However, I think this question is more appropriate for the [Blockchain Community of Practice](https://digital.gov/communities/blockchain/), rather than an issue on this repository.

If there is clear Acceptance Criteria as it relates to this site, please feel free to add it.
